---
# Grafana configuration
grafana_version: "latest"
grafana_port: "3000"
grafana_domain: "localhost"
grafana_data_dir: "/var/lib/grafana"
grafana_logs_dir: "/var/log/grafana"
grafana_plugins_dir: "/var/lib/grafana/plugins"

# Grafana admin
grafana_admin_user: "admin"
grafana_admin_password: "admin"

# Grafana datasource
grafana_datasource_name: "Prometheus"
grafana_datasource_url: "http://localhost:9090"
