---
- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    system: yes
    shell: /bin/false
    home: "{{ prometheus_data_dir }}"
    createhome: no

- name: Create prometheus group
  group:
    name: "{{ prometheus_group }}"
    system: yes

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download and extract Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}"

- name: Copy Prometheus binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_platform }}/{{ item }}"
    dest: "{{ prometheus_binary_dir }}/{{ item }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  loop:
    - prometheus
    - promtool
  notify: restart prometheus

- name: Copy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: restart prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify:
    - reload systemd
    - restart prometheus

- name: Download and extract Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ prometheus_platform }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.{{ prometheus_platform }}"

- name: Copy Node Exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ prometheus_platform }}/node_exporter"
    dest: "{{ prometheus_binary_dir }}/node_exporter"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  notify: restart node-exporter

- name: Create Node Exporter systemd service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: '0644'
  notify:
    - reload systemd
    - restart node-exporter

- name: Start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - prometheus
    - node-exporter
